package com.braintwinx.dto;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;

/**
 * Login credentials.
 *
 * <p>Length bounds exist so an oversized field is rejected at the boundary rather than reaching
 * BCrypt. BCrypt cost is paid per verification, so an unbounded password field is a cheap way to
 * make the server do expensive work.
 *
 * <p>No {@code toString()} is generated by hand and none should be added: a record's default
 * {@code toString()} would include the password, so this type must never be logged. It is
 * consumed immediately and discarded.
 */
public record LoginRequest(
        @NotBlank(message = "must not be blank")
        @Size(max = 64, message = "must be at most 64 characters")
        String username,

        @NotBlank(message = "must not be blank")
        @Size(max = 128, message = "must be at most 128 characters")
        String password) {

    /** Overridden so an accidental log statement cannot print the password. */
    @Override
    public String toString() {
        return "LoginRequest{username=" + username + ", password=[REDACTED]}";
    }
}
